Safari: quick hack to fix listener registration
ghostery/ghostery-dnr-extension pull request #87
Opened 2022-02-24 19:23 UTC by chrmod

Ephemeral background pages/service workers gets resumed only by listeners registered in the top-level scripts. In Safari, in order to user JavaScript modules we use background page instead of background scripts - this page is able to load scripts of type module. This works great, but scripts type=module by specification evaluates asynchronously (after a runloop tick). This makes listeners they register to not be considered top-level and in effect the browser wont resume the background on their respective events.

This PR introduces a hack - a simple top-level script with dummy listeners which roles is only to wake up the background when needed. The hack works, but  probably will miss the first event - again, because the proper background script registers its listeners after a runloop tick.

We should verify if the "proper" background script misses first event and if it does we may try to find another hack to let the the event be handled properly. An event queue comes as first thought but would have to guarantee:
* order of events 
* handling responses

2022-02-24 19:26 UTC, chrmod commented
Important: Safari 15 record the listeners at the onload event time.

2022-02-25 08:29 UTC, smalluban requested changes
I thought that vite will take stub.js, and push it to the dist, but it didn't. In one way it is understandable as it takes modules and pushes them to the dist.

However, what do you think to inline this script in HTML instead? I think it will take less code change, and if Safari will eventually support service workers (as I suppose this is the way they want to support es modules) we will not have to unhack `scripts/build.js`. Another advantage is not introducing source code paths in build script, as it should read manifest, and takes only files which are defined there.

2022-02-25 08:39 UTC, smalluban commented
About the skipped event, we can check it out with some logs in stub and main event listener, so if the catch both the same events.

2022-02-25 09:07 UTC, chrmod commented
have tried with inline script as my first try, but it was blocked by the CSP. We would have to allow unsafe-eval, which we should not.

2022-03-02 11:23 UTC, smalluban approved these changes
After a while of testing, it looks that there is quite a simple solution to the problem - we just need to add the `async` attribute to the script tag. According to the spec of modules loaded by script tag, those with `async` load and execute ASAP, they block parsing HTML (but when they are fetched and parsed), and what is most important, they block calling `load` event on the window (more info you can find here: https://gist.github.com/jakub-g/385ee6b41085303a53ad92c7c8afd7a6). 

The last point is most critical, as the Safari waits for the listeners until the load event is fired, so our background page is marked, and it runs after termination.

2022-03-02 11:24 UTC, merged