Add download script for fetching dynamically the DNR lists
ghostery/ghostery-dnr-extension pull request #99
Opened 2022-03-31 14:04 UTC by smalluban

Fixes #30. Fixes #31. Fixes #94.

* Removes hardcoded reference to external path (used by vendor copy)
* Adds `download-dnr-lists` npm script
* The script is added to the `postinstall` command, but it should be called before the final build for the release

2022-03-31 14:58 UTC, philipp-classen commented
Not sure how to solve it best, but some things that I noticed, so I'm putting them here as text. (I tried to use it as someone who never worked with the repository before):

README is outdated:
* I tried to follow the steps in the README (`npm ci` && `npm run start`), but it fails; part of it is that I have `ignore-scripts=true` configured in `~/.npmrc`, but even when I run `npm run postinstall` before `npm run start` it fails (see error below). If I disable the option, it works but I have to disable it globally (the normal workarounds `npm --ignore-scripts=false` or manually running `npm run postinstall` fail).
* The `npm run build` step is needed before `npm run start`.
* If you don't have access to the private repository, the placeholder code kicks (which is expected). Would be nice to show more information that it is OK to continue with the fallback; currently, I would see only the error messages and assume the installation failed

With the placeholders, you can only test parts of the extension. The tracker preview works, but nothing tracking related will be possible to test, which is a core feature. What I was trying here was to have a minimal set of rules to support at least one test page: https://github.com/ghostery/ghostery-dnr-extension/pull/19

Maybe we can have something like that? Otherwise, I fear it is not possible for anyone from the outside to do much.

---

This is the error that `npm run postinstall` throws for me:

```
hil@ghostery:/home/.snapshots/tmp-home-2022-03-31--16-22-51--3434116-28538/phil/github/ghostery-dnr-extension (fix-download-dnr-lists)$ git clean -d -x -f
phil@ghostery:/home/.snapshots/tmp-home-2022-03-31--16-22-51--3434116-28538/phil/github/ghostery-dnr-extension (fix-download-dnr-lists)$ npm ci
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 620 packages, and audited 621 packages in 4s

69 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
phil@ghostery:/home/.snapshots/tmp-home-2022-03-31--16-22-51--3434116-28538/phil/github/ghostery-dnr-extension (fix-download-dnr-lists)$ npm run postinstall

> @ghostery/dnr-extension@9.3.0 postinstall
> vendor-copy && npm run download-cosmetics && npm run download-dnr-lists

/home/.snapshots/tmp-home-2022-03-31--16-22-51--3434116-28538/phil/github/ghostery-dnr-extension/node_modules/@whotracksme/webextension-packages/packages => /home/.snapshots/tmp-home-2022-03-31--16-22-51--3434116-28538/phil/github/ghostery-dnr-extension/src/vendor/@whotracksme

> @ghostery/dnr-extension@9.3.0 download-cosmetics
> node scripts/download-cosmetics.js


> @ghostery/dnr-extension@9.3.0 download-dnr-lists
> node scripts/download-dnr-lists.js

Cloning into 'tmp/dnr-lists'...
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.

added 329 packages, and audited 330 packages in 3s

35 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> @ghostery/dnr-lists@1.0.0 start
> npm run download && npm run build


> @ghostery/dnr-lists@1.0.0 download
> npm run download-rules && npm run download-trackerdb


> @ghostery/dnr-lists@1.0.0 download-rules
> node ./scripts/download-rules.mjs


> @ghostery/dnr-lists@1.0.0 download-trackerdb
> sh ./scripts/download-trackerdb.sh

+ aws s3 cp --no-sign-request s3://data.whotracks.me/trackerdb.sql ./lists/
download: s3://data.whotracks.me/trackerdb.sql to lists/trackerdb.sql

> @ghostery/dnr-lists@1.0.0 build
> node src/index.mjs

node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module '/home/.snapshots/tmp-home-2022-03-31--16-22-51--3434116-28538/phil/github/ghostery-dnr-extension/tmp/dnr-lists/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node'
Require stack:
- /home/.snapshots/tmp-home-2022-03-31--16-22-51--3434116-28538/phil/github/ghostery-dnr-extension/tmp/dnr-lists/node_modules/sqlite3/lib/sqlite3-binding.js
- /home/.snapshots/tmp-home-2022-03-31--16-22-51--3434116-28538/phil/github/ghostery-dnr-extension/tmp/dnr-lists/node_modules/sqlite3/lib/sqlite3.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/.snapshots/tmp-home-2022-03-31--16-22-51--3434116-28538/phil/github/ghostery-dnr-extension/tmp/dnr-lists/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/.snapshots/tmp-home-2022-03-31--16-22-51--3434116-28538/phil/github/ghostery-dnr-extension/tmp/dnr-lists/node_modules/sqlite3/lib/sqlite3-binding.js',
    '/home/.snapshots/tmp-home-2022-03-31--16-22-51--3434116-28538/phil/github/ghostery-dnr-extension/tmp/dnr-lists/node_modules/sqlite3/lib/sqlite3.js'
  ]
}
cp: no such file or directory: tmp/dnr-lists/build/*.json
```

2022-03-31 17:21 UTC, chrmod requested changes
This is unfortunately preemptive. Safari is only able to support `urlFilter` since `15.4` so until it gets some serious adoption we have to stick with `regexFilter`. 

Currently we are using cliqz/adblocker `safari` rules which we convert to `drn` `regexFilter` format.

2022-04-01 07:29 UTC, smalluban commented
@philipp-classen Thanks for the deep review with testing. Here you have my thoughts:
* The README is indeed outdated, but it also does not follow the latest changes with the build step. Changes from this PR do not change the flow, they rather simplify it. I will update the README (but it is not the scope of this PR)
* Your error message is related to the broken installation of the sqlite3 library (it needs a natively compiled part). Are you sure, that you are using the correct node version? You should be at least on node 16.x+
* About the list content I have mixed feelings. We can provide some example structure, but then if the structure will change, we will also need to update the examples. The current solution is temporary, as we are going to move static assets from CDN soon, so then we will fetch them regardless of the access to some private repository.

2022-04-01 07:31 UTC, smalluban commented
> This is unfortunately preemptive. Safari is only able to support `urlFilter` since `15.4` so until it gets some serious adoption we have to stick with `regexFilter`.
> 
> Currently we are using cliqz/adblocker `safari` rules which we convert to `drn` `regexFilter` format.

@chrmod This PR does not change the lists at all. It only moves the generation from outside path to the internal script. It works the same as before. What do you mean?

2022-04-01 09:42 UTC, philipp-classen commented
> @philipp-classen Thanks for the deep review with testing. Here you have my thoughts:
> 
>     * The README is indeed outdated, but it also does not follow the latest changes with the build step. Changes from this PR do not change the flow, they rather simplify it. I will update the README (but it is not the scope of this PR)
> 
>     * Your error message is related to the broken installation of the sqlite3 library (it needs a natively compiled part). Are you sure, that you are using the correct node version? You should be at least on node 16.x+

I'm on v16.14.2, but I think it is caused because some scripts in the cloned repository was not run if `ignore-scripts=true` is set globally.
 
> 
>     * About the list content I have mixed feelings. We can provide some example structure, but then if the structure will change, we will also need to update the examples. The current solution is temporary, as we are going to move static assets from CDN soon, so then we will fetch them regardless of the access to some private repository.

OK, if there is a plan to support it later we can start with the current empty placeholders

2022-04-01 10:30 UTC, chrmod approved these changes
OK, I get it know. Was previously thinking that you download the adblocker-filters lists directly. The PR looks great!

2022-04-01 13:43 UTC, merged